version: "3.8"

services:
  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - chat-app-network

  # PostgreSQL Service
  postgres:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=chat_app
    networks:
      - chat-app-network

volumes:
  redis-data:
  postgres-data:

networks:
  chat-app-network:
    driver: bridge
